// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cslqdvufvgsxnpwenilc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbHFkdnVmdmdzeG5wd2VuaWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTc0ODIsImV4cCI6MjA2NTY5MzQ4Mn0.C9ozP-A-zRllRPQ3w1enpAMptkwAH_B7vqIHirz49es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});